package Ejercicio1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alumno
 */
public class frmCalculadoraForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
        private double primerNum = 0;
        private double segundoNum = 0;
        private String operacion = "";
    public frmCalculadoraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIgual = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta1 = new javax.swing.JButton();
        btnCero1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, -1));

        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        btnDos.setText("2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, -1));

        btnTres.setText("3");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        getContentPane().add(btnTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 70, -1));

        btnCuatro.setText("4");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, -1));

        btnSiete.setText("7");
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));

        btnOcho.setText("8");
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        getContentPane().add(btnOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, -1));

        btnNueve.setText("9");
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        getContentPane().add(btnNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 70, -1));

        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 40));

        btnBorrar.setText("<-");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, -1));

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, -1));

        btnMultiplicar.setText("X");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, -1));

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 70, -1));

        btnResta1.setText("-");
        btnResta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnResta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 70, -1));

        btnCero1.setText("0");
        btnCero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCero1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        try {
        primerNum = Double.parseDouble(txtResultado.getText());
        operacion = "/";
        txtResultado.setText("");
    } catch (NumberFormatException e) {
        txtResultado.setText("Error de formato");
    }
        
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
        try {
        primerNum = Double.parseDouble(txtResultado.getText());
        operacion = "*";
        txtResultado.setText("");
    } catch (NumberFormatException e) {
        txtResultado.setText("Error de formato");
    }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        try {
        primerNum = Double.parseDouble(txtResultado.getText());
        operacion = "+";
        txtResultado.setText("");
    } catch (NumberFormatException e) {
        txtResultado.setText("Error de formato");
    }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        String texto = txtResultado.getText();
    if (!texto.isEmpty()) {
        txtResultado.setText(texto.substring(0, texto.length() - 1));
    }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCero1ActionPerformed
        // TODO add your handling code here:
        txtResultado.setText(txtResultado.getText() + "0");
    }//GEN-LAST:event_btnCero1ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
         try {
        segundoNum = Double.parseDouble(txtResultado.getText());
        double resultado = 0;

        switch (operacion) {
            case "+" -> resultado = primerNum + segundoNum;
            case "-" -> resultado = primerNum - segundoNum;
            case "*" -> resultado = primerNum * segundoNum;
            case "/" -> {
                if (segundoNum == 0) {
                    txtResultado.setText("No se puede dividir por cero");
                    return;
                }
                resultado = primerNum / segundoNum;
            }
            default -> {
                txtResultado.setText("Operación no válida");
                return;
            }
        }

        txtResultado.setText(String.valueOf(resultado));
        operacion = "";
    } catch (NumberFormatException e) {
        txtResultado.setText("Error de formato");
    }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnResta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResta1ActionPerformed
        // TODO add your handling code here:
        try {
        primerNum = Double.parseDouble(txtResultado.getText());
        operacion = "-";
        txtResultado.setText("");
    } catch (NumberFormatException e) {
        txtResultado.setText("Error de formato");
    }
    }//GEN-LAST:event_btnResta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadoraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadoraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCero1;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnResta1;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
