/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio3;

import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author Martin
 */
public class frmSelectorLenguajeForm extends javax.swing.JFrame {
    
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    /**
     * Creates new form SelectorLenguajeForm
     */
    public frmSelectorLenguajeForm() {
        initComponents();
        cargarLenguajes();
        configurarEventos();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstLenguajes = new javax.swing.JList<>();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLenguajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 210));

        label1.setName(""); // NOI18N
        label1.setText("Selecciona un lenguaje (con doble click):");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSelectorLenguajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSelectorLenguajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSelectorLenguajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSelectorLenguajeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectorLenguajeForm().setVisible(true);
            }
        });
    }
    private void cargarLenguajes() {
    modeloLista.addElement("Java");
    modeloLista.addElement("Python");
    modeloLista.addElement("C++");
    modeloLista.addElement("JavaScript");
    modeloLista.addElement("C#");
    modeloLista.addElement("Go");

    lstLenguajes.setModel(modeloLista);
    lstLenguajes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}

private void configurarEventos() {
    lstLenguajes.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent evt) {
            if (evt.getClickCount() == 2) {
                String lenguaje = lstLenguajes.getSelectedValue();
                mostrarInfo(lenguaje);
            }
        }
    });
}

private void mostrarInfo(String lenguaje) {
    String info;

    switch (lenguaje) {
        case "Java":
            info = "Java: Lenguaje robusto, orientado a objetos y multiplataforma.";
            break;
        case "Python":
            info = "Python: Versátil y potente, excelente para IA y scripts.";
            break;
        case "C++":
            info = "C++: Alto rendimiento, perfecto para videojuegos y sistemas.";
            break;
        case "JavaScript":
            info = "JavaScript: El lenguaje esencial para desarrollo web moderno.";
            break;
        case "C#":
            info = "C#: Creado por Microsoft, usado en apps y videojuegos.";
            break;
        case "Go":
            info = "Go: Diseñado por Google, ideal para backend escalable.";
            break;
        default:
            info = "No hay datos disponibles.";
    }

    JOptionPane.showMessageDialog(this, info, "Detalles del Lenguaje", JOptionPane.INFORMATION_MESSAGE);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JList<String> lstLenguajes;
    // End of variables declaration//GEN-END:variables
}
